<?php

namespace Database\Seeders;

use App\Models\Disclaimer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DisclaimerSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Disclaimer::truncate();

        Disclaimer::create([
            'title' => 'Disclaimer Update',
            'content' => <<<'HTML'
<p>
OOHAPP hereby grants you access to OOHAPP.com ("the Website") and invites you to access the independent services offered here.
</p>

<h3><strong>1. Definitions and Key Terms</strong></h3>
<p>
To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, they are strictly defined as:
</p>

<ul>
    <li><strong>Cookie:</strong> Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you.</li>
    <li><strong>Company:</strong> When this policy mentions "Company", "we", "us", or "our", it refers to OOHAPP.</li>
    <li><strong>Service:</strong> Refers to the service provided by OOHAPP.</li>
    <li><strong>Website:</strong> OOHAPP's site, accessible via OOHAPP.com.</li>
    <li><strong>You:</strong> A person or entity registered with OOHAPP to use the Services.</li>
</ul>

<h3><strong>2. Limited Liability</strong></h3>
<p>
We endeavour to update and/or supplement the content of our services on a regular basis. Despite our care and attention, content may be incomplete or incorrect.
</p>

<p>
The materials offered are provided without any form of guarantee or claim to their correctness and may be changed at any time without notice.
</p>

<p>
OOHAPP does not warrant that the website will be error-free or uninterrupted. While we strive to provide quality links, we have no control over third-party websites.
</p>

<h3><strong>3. Links to Other Websites Disclaimer</strong></h3>
<p>
This Disclaimer applies only to the Services. The Services may contain links to other websites not operated or controlled by us.
</p>

<p>
We strongly advise you to review the Privacy Policy and Terms & Conditions of every site you visit.
</p>

<p>
We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
</p>
HTML,
            'effective_date' => '2025-01-01',
            'is_active' => 1,
        ]);
    }
}
