<?php

namespace Database\Seeders;

use App\Models\Disclaimer;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DisclaimerSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        Disclaimer::truncate();

        Disclaimer::create([
            'title' => 'Disclaimer',
            'content' => <<<'HTML'

<h2><strong>DISCLAIMER</strong></h2>

<p>
OOHAPP hereby grants you access to <a href="https://www.oohapp.io" target="_blank">https://www.oohapp.io/</a> (the “Website”) and invites you to access and use the services offered on this platform.
The services provided through this website are indigenous in nature and are made available subject to the terms set out in this disclaimer and other applicable policies of OOHAPP.
</p>

<p>
The information and services available on the website are provided for general informational and operational purposes only.
Your access to and use of the website and services is entirely at your own discretion and risk.
</p>

<hr>

<h2><strong>DEFINITIONS AND KEY TERMS</strong></h2>

<p>
To help explain this disclaimer as clearly as possible, whenever the following terms are referenced, they shall have the meanings defined below:
</p>

<p><strong>Cookie</strong></p>
<p>
A small amount of data generated by a website and stored by your web browser.
Cookies are used to identify your browser, provide analytics, remember user preferences,
and store certain information such as language selection or login details.
</p>

<p><strong>Company</strong></p>
<p>
When this Disclaimer mentions “Company,” “we,” “us,” or “our,” it refers to OOHAPP,
which is responsible for the operation of the Website and the handling of information under this Disclaimer.
</p>

<p><strong>Service / Services</strong></p>
<p>
Refers to the services provided by OOHAPP as described on the website,
within applicable terms and conditions (if available), and through this platform.
</p>

<p><strong>Website</strong></p>
<p>
Refers to OOHAPP’s official website, accessible at
<a href="https://www.oohapp.io/" target="_blank">https://www.oohapp.io/</a>.
</p>

<p><strong>You / User</strong></p>
<p>
Refers to any individual or legal entity that accesses, browses,
or is registered with OOHAPP to use the Services.
</p>

<hr>

<h2><strong>LIMITED LIABILITY</strong></h2>

<p>
We endeavor to update, maintain, and supplement the content of our services on a regular basis.
However, despite our reasonable care and attention, the content available on the Website may occasionally be incomplete,
outdated, inaccurate, or incorrect.
</p>

<p>
All materials and information provided through the Services are offered without any warranty, guarantee,
or representation, express or implied, as to their accuracy, completeness, or reliability.
The content on the website may be changed, modified, updated, or removed at any time without prior notice.
</p>

<p>
In particular, all prices, listings, specifications, and related information displayed on the Services are subject to
typographical, technical, or programming errors. OOHAPP assumes no liability for the consequences of such errors.
No agreement, transaction, or obligation shall be deemed to arise solely on the basis of such errors.
</p>

<p>
OOHAPP shall not be held liable for any direct or indirect loss, damage,
or inconvenience arising from reliance on the content available on the Services.
</p>

<hr>

<h2><strong>THIRD-PARTY LINKS AND EXTERNAL WEBSITES</strong></h2>

<p>
Our services may contain hyperlinks to websites or services operated by third parties.
Users may visit other websites by following these hyperlinks to external sites
that are not owned, operated, or controlled by OOHAPP.
</p>

<p>
While we strive to provide links to useful, ethical, and relevant websites,
we have no control over the content, nature, accuracy, or availability of such external websites.
The inclusion of any link does not imply a recommendation or endorsement of all the content found on those websites.
</p>

<p>
Website owners and content may change without notice,
and such changes may occur before we have the opportunity to remove links
that may no longer be valid or appropriate.
</p>

<p>
Please note that when you leave our services, other websites may have different privacy policies,
terms of use, and practices, which are beyond our control.
We strongly encourage you to review the privacy policies and terms of service
of any external website before engaging in any business or transactions
or uploading any personal or sensitive information.
</p>

<hr>

<h2><strong>LINKS TO OTHER WEBSITES DISCLAIMER</strong></h2>

<p>
This disclaimer applies only to the services provided by OOHAPP.
</p>

<p>
The Services may include links to third-party websites that are not operated,
maintained, or controlled by us. We do not investigate, monitor, or verify such websites
for accuracy, completeness, or reliability, and we are not responsible for the content,
opinions, or information expressed on such websites.
</p>

<p>
When you click on a third-party link, you will be redirected to that third party’s website.
At that point, OOHAPP’s Privacy Policy and Disclaimer will no longer apply,
and your interaction with that website will be governed by the third party’s own rules,
policies, and practices.
</p>

<p>
Third parties may use their own cookies or other tracking technologies to collect information about you.
OOHAPP has no control over and assumes no responsibility for the content,
privacy policies, data practices, or operations of any third-party website or service.
</p>

<hr>

<h2><strong>USER ACKNOWLEDGEMENT</strong></h2>

<p>
By accessing and using the Website and Services,
you acknowledge that you have read, understood,
and agreed to this Disclaimer and accept full responsibility for your use of the Services.
</p>

<hr>

<h2><strong>CONTACT INFORMATION</strong></h2>

<p>
If you have any questions or concerns regarding this disclaimer, you may contact us at:
</p>

<p>
<strong>OOHAPP</strong><br>
Email: <a href="mailto:support@oohapp.io">support@oohapp.io</a>
</p>

HTML,
            'effective_date' => '2025-01-01',
            'is_active' => 1,
        ]);
    }
}
