<?php

namespace Database\Seeders;

use App\Models\Disclaimer;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DisclaimerSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        Disclaimer::truncate();

        Disclaimer::create([
            'title' => 'Disclaimer',
            'content' => <<<'HTML'

<h2 style="padding-bottom:5px; font-size:24px; font-weight:700;">
    Disclaimer
</h2>

<p>
OOHAPP hereby grants you access to OOHAPP.com/ ("the Website") and invites you to access the indigenous services offered here.
</p>

<hr>

<h2><strong>1. Definitions and key terms:</strong></h2>

<p>
To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, are strictly defined as:
</p>

<p><strong>Cookie</strong></p>
<p>
small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
</p>

<p><strong>Company</strong></p>
<p>
when this policy mentions "Company", "we", "us", or "our", it refers to OOHAPP that is responsible for your information under this Disclaimer.
</p>

<p><strong>Service</strong></p>
<p>
refers to the service provided by OOHAPP as described in the relative terms (if available) and on this platform
</p>

<p><strong>Website</strong></p>
<p>
OOHAPP's site, which can be accessed via this URL: OOHAPP.com.
</p>

<p><strong>You</strong></p>
<p>
a person or entity that is registered with OOHAPP to use the Services.
</p>

<hr>

<h2><strong>2. LIMITED LIABILITY</strong></h2>

<p>
We endeavour to update and/or supplement the content of our service on a regular basis. Despite our care and attention, content may be incomplete and/or incorrect. The materials we offer are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from us. Particularly, all prices on our service are stated subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors. We shall not bear any liability for hyperlinks to websites or services of third parties included on our service. From our user can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites.
</p>

<p>
These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice before we have the opportunity to remove a link which may have gone 'bad'. Please be also aware that when you leave our service, other sites may have different privacy policies and terms which are beyond our control.
</p>

<p>
Please be sure to check the Privacy Policies of these sites as well as their 'Terms of Service' before engaging in any business or uploading any information.
</p>

<hr>

<h2><strong>3. LINKS TO OTHER WEBSITE DISCLAIMER:</strong></h2>

<p>
This Disclaimer applies only to the Services. The Services may contain links to other websites not operated or controlled by us. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you. If You click on a third party link, You be directed to that third party's site. We strongly advise You to review the Privacy Policy and Terms of every site You visit.
</p>

<p>
We have no control over and assume no responsibility for the content, privacy policies or practices of any third party site services.
</p>

HTML,
            'effective_date' => '2025-01-01',
            'is_active' => 1,
        ]);
    }
}