<?php

namespace Modules\Import\Services;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Modules\Import\Entities\InventoryImportBatch;
use Modules\Import\Entities\InventoryImportStaging;
use App\Models\Hoarding;
use Modules\Hoardings\Models\OOHHoarding;
use Modules\Hoardings\Models\HoardingMedia;
use Modules\DOOH\Models\DOOHScreen;
use Modules\DOOH\Models\DOOHScreenMedia;
use Exception;

class ImportApprovalService
{
    /**
     * Process batch approval and create hoardings
     *
     * @param InventoryImportBatch $batch
     * @return array
     * @throws Exception
     */
    public function approveBatch(InventoryImportBatch $batch): array
    {
        try {
            // Validate batch status
            $this->validateBatchStatus($batch);

            $createdCount = 0;
            $failedCount = 0;

            // Wrap everything in transaction for atomicity
            DB::transaction(function () use ($batch, &$createdCount, &$failedCount) {
                // Get all valid staging records with eager loading
                $validRows = $batch->stagingRecords()
                    ->valid()
                    ->get();

                if ($validRows->isEmpty()) {
                    throw new Exception('No valid records found in batch to approve');
                }

                \Log::info('Starting batch approval', [
                    'batch_id' => $batch->id,
                    'valid_records' => $validRows->count(),
                ]);

                foreach ($validRows as $stagingRow) {
                    try {
                        $this->processRow($batch, $stagingRow);
                        $createdCount++;
                    } catch (Exception $e) {
                        $failedCount++;
                        \Log::error('Failed to process staging row', [
                            'batch_id' => $batch->id,
                            'row_id' => $stagingRow->id,
                            'code' => $stagingRow->code,
                            'error' => $e->getMessage(),
                        ]);
                        
                        // Mark row as failed
                        $stagingRow->markAsInvalid('Processing error: ' . $e->getMessage());
                        
                        // Don't throw - continue processing other rows
                    }
                }

                // Update batch status after successful processing
                $batch->updateStatus('completed');

                \Log::info('Batch approval completed', [
                    'batch_id' => $batch->id,
                    'created' => $createdCount,
                    'failed' => $failedCount,
                ]);
            }, attempts: 3);

            return [
                'success' => true,
                'created_count' => $createdCount,
                'failed_count' => $failedCount,
                'total_processed' => $createdCount + $failedCount,
            ];
        } catch (Exception $e) {
            \Log::error('Batch approval failed', [
                'batch_id' => $batch->id,
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);

            throw $e;
        }
    }

    /**
     * Validate batch is in correct status for approval
     *
     * @param InventoryImportBatch $batch
     * @throws Exception
     */
    protected function validateBatchStatus(InventoryImportBatch $batch): void
    {
        if ($batch->status !== 'processed') {
            throw new Exception(
                "Batch must be in 'processed' status to approve. Current status: {$batch->status}"
            );
        }

        if ($batch->valid_rows === 0) {
            throw new Exception('No valid rows to process in this batch');
        }
    }

    /**
     * Process single staging row to create hoarding and related records
     *
     * @param InventoryImportBatch $batch
     * @param InventoryImportStaging $stagingRow
     * @throws Exception
     */
    protected function processRow(InventoryImportBatch $batch, InventoryImportStaging $stagingRow): void
    {
        // STEP 1: Create parent Hoarding record
        $hoarding = Hoarding::create([
            'vendor_id' => $batch->vendor_id,
            'title' => $stagingRow->code, // Temporary, will be auto-generated by model
            'hoarding_type' => $stagingRow->media_type,
            'category' => $stagingRow->getExtraAttribute('category', null),
            'address' => $stagingRow->getExtraAttribute('address', null),
            'city' => $stagingRow->city,
            'state' => $stagingRow->getExtraAttribute('state', null),
            'locality' => $stagingRow->getExtraAttribute('locality', null),
            'pincode' => $stagingRow->getExtraAttribute('pincode', null),
            'latitude' => $stagingRow->getExtraAttribute('latitude', null),
            'longitude' => $stagingRow->getExtraAttribute('longitude', null),
            'base_monthly_price' => $stagingRow->getExtraAttribute('base_monthly_price', 0),
            'monthly_price' => $stagingRow->getExtraAttribute('monthly_price', 0),
            'currency' => $stagingRow->getExtraAttribute('currency', 'INR'),
            'status' => 'pending_approval',
        ]);

        if (!$hoarding) {
            throw new Exception('Failed to create hoarding record');
        }

        \Log::info('Created hoarding', [
            'hoarding_id' => $hoarding->id,
            'vendor_id' => $batch->vendor_id,
            'code' => $stagingRow->code,
        ]);

        // STEP 2: Create type-specific records
        if ($stagingRow->media_type === 'ooh') {
            $this->createOOHRecords($hoarding, $stagingRow);
        } elseif ($stagingRow->media_type === 'dooh') {
            $this->createDOOHRecords($hoarding, $stagingRow);
        } else {
            throw new Exception("Unknown media type: {$stagingRow->media_type}");
        }
    }

    /**
     * Create OOH hoarding records (OOHHoarding + HoardingMedia)
     *
     * @param Hoarding $hoarding
     * @param InventoryImportStaging $stagingRow
     * @throws Exception
     */
    protected function createOOHRecords(Hoarding $hoarding, InventoryImportStaging $stagingRow): void
    {
        try {
            // Create OOHHoarding record
            $oohHoarding = OOHHoarding::create([
                'hoarding_id' => $hoarding->id,
                'width' => $stagingRow->width,
                'height' => $stagingRow->height,
                'measurement_unit' => $stagingRow->getExtraAttribute('measurement_unit', 'ft'),
            ]);

            if (!$oohHoarding) {
                throw new Exception('Failed to create OOH hoarding record');
            }

            \Log::info('Created OOH hoarding', [
                'ooh_hoarding_id' => $oohHoarding->id,
                'hoarding_id' => $hoarding->id,
                'width' => $stagingRow->width,
                'height' => $stagingRow->height,
            ]);

            // Create HoardingMedia record if image exists
            if ($stagingRow->image_name) {
                $media = HoardingMedia::create([
                    'hoarding_id' => $hoarding->id,
                    'file_path' => $this->resolveImagePath($stagingRow),
                    'media_type' => 'image',
                    'is_primary' => true,
                    'sort_order' => 0,
                ]);

                if (!$media) {
                    throw new Exception('Failed to create hoarding media record');
                }

                \Log::info('Created hoarding media', [
                    'media_id' => $media->id,
                    'hoarding_id' => $hoarding->id,
                    'image' => $stagingRow->image_name,
                ]);
            }
        } catch (Exception $e) {
            throw new Exception("Failed to create OOH records: {$e->getMessage()}");
        }
    }

    /**
     * Create DOOH screen records (DOOHScreen + DOOHScreenMedia)
     *
     * @param Hoarding $hoarding
     * @param InventoryImportStaging $stagingRow
     * @throws Exception
     */
    protected function createDOOHRecords(Hoarding $hoarding, InventoryImportStaging $stagingRow): void
    {
        try {
            // Create DOOHScreen record
            $doohScreen = DOOHScreen::create([
                'hoarding_id' => $hoarding->id,
                'screen_type' => $stagingRow->getExtraAttribute('screen_type', 'led'),
                'width' => $stagingRow->width,
                'height' => $stagingRow->height,
                'measurement_unit' => $stagingRow->getExtraAttribute('measurement_unit', 'px'),
                'slot_duration_seconds' => $stagingRow->getExtraAttribute('slot_duration_seconds', 10),
                'price_per_slot' => $stagingRow->getExtraAttribute('price_per_slot', 0),
            ]);

            if (!$doohScreen) {
                throw new Exception('Failed to create DOOH screen record');
            }

            \Log::info('Created DOOH screen', [
                'screen_id' => $doohScreen->id,
                'hoarding_id' => $hoarding->id,
                'width' => $stagingRow->width,
                'height' => $stagingRow->height,
            ]);

            // Create DOOHScreenMedia record if image exists
            if ($stagingRow->image_name) {
                $media = DOOHScreenMedia::create([
                    'dooh_screen_id' => $doohScreen->id,
                    'file_path' => $this->resolveImagePath($stagingRow),
                    'media_type' => 'image',
                    'is_primary' => true,
                    'sort_order' => 0,
                ]);

                if (!$media) {
                    throw new Exception('Failed to create DOOH screen media record');
                }

                \Log::info('Created DOOH screen media', [
                    'media_id' => $media->id,
                    'screen_id' => $doohScreen->id,
                    'image' => $stagingRow->image_name,
                ]);
            }
        } catch (Exception $e) {
            throw new Exception("Failed to create DOOH records: {$e->getMessage()}");
        }
    }

    /**
     * Resolve image file path from staging row
     *
     * @param InventoryImportStaging $stagingRow
     * @return string
     */
    protected function resolveImagePath(InventoryImportStaging $stagingRow): string
    {
        // Images are stored in: storage/app/imports/{batch_id}/images/{image_name}
        $imagePath = "imports/{$stagingRow->batch_id}/images/{$stagingRow->image_name}";

        $disk = Storage::disk('local');

        if ($disk->exists($imagePath)) {
            return $imagePath;
        }

        $searchRoot = "imports/{$stagingRow->batch_id}/images";
        if ($disk->exists($searchRoot)) {
            foreach ($disk->allFiles($searchRoot) as $file) {
                if (basename($file) === $stagingRow->image_name) {
                    return $file;
                }
            }
        }

        return $imagePath;
    }
}
